
<!DOCTYPE html>
<html lang="en">
	<?php include('head.php') ?>
	<body>
		<?php $home = true ?>
		<?php include('navbar.php') ?>

		<!-- Begin page content -->
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<div class="text-center">
						<!-- Generated by http://www.flickrslideshow.com -->
						<div style="width:768px;height:466px;text-align:center;margin:auto;" ><object width="768" height="466" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"> <param name="flashvars" value="offsite=true&amp;lang=en-us&amp;page_show_url=%2Fphotos%2Fdalwits%2Fsets%2F72157646624237069%2Fshow&amp;page_show_back_url=%2Fphotos%2Fdalwits%2Fsets%2F72157646624237069%2F&amp;set_id=72157646624237069" /> <param name="allowFullScreen" value="false" /> <param name="src" value="https://www.flickr.com/apps/slideshow/show.swf?v=71649" /> <embed width="768" height="466" type="application/x-shockwave-flash" src="https://www.flickr.com/apps/slideshow/show.swf?v=71649" flashvars="offsite=true&amp;lang=en-us&amp;page_show_url=%2Fphotos%2Fdalwits%2Fsets%2F72157646624237069%2Fshow&amp;page_show_back_url=%2Fphotos%2Fdalwits%2Fsets%2F72157646624237069%2F&amp;set_id=72157646624237069" allowFullScreen="false" /> </object></div>
						<h1>
							PROMOTING <b>YOUND WOMEN</b><br>
							<small>TO CONSIDER A CAREER IN TECHNOLOGY</small>
						</h1>
					</div>	
				</div>
			</div>

			<hr>

			<div class="content">
				<div class="row">
					<div class="col-xs-12 col-sm-8 col-sm-offset-2">
						<p class="lead">
							The Dalhousie Women in Technology Society (WiTS) works towards
							the promotion and support of women in computer science and technology
							related disciplines.
						</p>
						<p>
							We are a group female and male students meet, host events, organize lectures,
							and reach out to groups in the community for technology related projects.
							You can find us having our breakfast meetings every other week in the Atrium
							or in a designated room in the CS building.
						</p>

						
					</div>
				</div>

				<hr>

				<div class="row text-center">
					<div class="col-xs-12 quote-text">
						<h1>
							&ldquo;We need more women in the field. They provide balance to the IT culture.
							Our work is more about building and leveraging working relationships with our multitudes of clients.&rdquo;
						</h1>
					</div>
					<div class="col-xs-12">
						<h3>
							Dwight Fischer <br>
							<small>Assistant Vice-President of Information Technology Services at Dalhousie University</small>
						</h3>
					</div>
				</div>
			</div>
			

			<hr>

			<div class="row">
				<div class="col-xs-4">
					<img src="images/FCS.png" class="img-responsive" alt="Faculty of Computer Science">
				</div>
				<div class="col-xs-4">
					<img src="images/CanWIT.png" class="img-responsive" alt="Canadian Women in Technology">
				</div>
				<div class="col-xs-4">
					<img src="images/CSS.png" class="img-responsive" alt="Computer Science Society">
				</div>
			</div>
		</div>

		<?php include('footer.php') ?>
		<?php include('javascript.php') ?>
	</body>
</html>
